### ISSUE TITLE
Connect to parse-server after migrating to heroku/mongo

### ISSUE THREAD

**Issue by michaelbina** [ivnivnch/angular-parse#4]
I am migrating my app from the Parse servers to Heroku/MongoLabs with the parse-server express code running.  I've been able to connect my iOS client to the new api by specifying the url in the config.  I'm wondering if there is a way to do something similar with this library because I was already using it for an accompanying Angular app.  Any help would be appreciated.  If it's not already built in, maybe you can point me to where I can modify the library to fit my needs.

**Comment by ivnivnch** [comment]
This lib just [wraps window.Parse object](https://github.com/ivnivnch/angular-parse/blob/master/webpack.config.js#L12)
